### ISSUE TITLE
Move the results

### ISSUE THREAD

**Issue by CesarHerreraG** [fulvio999/iMoon#5]
With your finger to display everything in all screen sizes.

**Comment by fulvio999** [comment]
With the last App version (1.6) the page with the results is scrollable so that everything is visible
What device are you using ? please (if possible) attach some screenshots.

**Comment by CesarHerreraG** [comment]
BQ E4.5

**Comment by CesarHerreraG** [comment]
I'm not able to send the screenshot

**Comment by CesarHerreraG** [comment]
With 1.6.1 very good in landscape. Thanks.
